plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vt100.ime'
    compileSdk 35

    defaultConfig {
        applicationId 'com.vt100.ime'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
}
